### ISSUE TITLE
Settings: Handle change of the explorer

### ISSUE THREAD

**Issue by tiero** [vulpemventures/marina#105]

**Comment by tiero** [comment]
@wiz @softsimon

Hey guys, working on adding Mempool support in Marina. One cool feature of Esplora is the way to encode in querystring the blinders that let the Esplora frontend to unblind in the browser the transaction and show the details of inputs/outputs.

Example: https://blockstream.info/liquid/tx/16e987d626adfa4dbf50312a9b8e31571531f9b8e5407c49d8e0b3dc4ac707ac#blinded=160252405,ce091c998b83c78bb71a632313ba3760f1763d9cfcffae02258ffa9865a37bd2,a50c70e9049a6a49f895b6bbadf7d4c212b1940b9748603fc006d3de1092bcbd,8b0ec267d4260102439c29abeb6fa606997cc4ee86fcd996bd82a462a78ee3c8,26252,6f0279e9ed041c3d710a9f57d0c02928416460c4b722ae3457a11eec381c526d,57bfaf037eea2f910e73c39e543306317ecda6d9e8c30a3273f92b3447cb22f4,bc230d8ee0d9503d4cd6081facd71f0e37a45fc2c475eae154da90ebee1ae087


Is it possible to do it on mempool as well?

**Comment by wiz** [comment]
Yes, you can subscribe to  https://github.com/mempool/mempool/issues/523 and we will prioritize it for you.

**Comment by tiero** [comment]
Thanks. We can ship already, mempool will simply ignore the extra querystring.

ie. 

Frontend 

https://mempool.space/liquid/tx/16e987d626adfa4dbf50312a9b8e31571531f9b8e5407c49d8e0b3dc4ac707ac#blinded=160252405,ce091c998b83c78bb71a632313ba3760f1763d9cfcffae02258ffa9865a37bd2,a50c70e9049a6a49f895b6bbadf7d4c212b1940b9748603fc006d3de1092bcbd,8b0ec267d4260102439c29abeb6fa606997cc4ee86fcd996bd82a462a78ee3c8,26252,6f0279e9ed041c3d710a9f57d0c02928416460c4b722ae3457a11eec381c526d,57bfaf037eea2f910e73c39e543306317ecda6d9e8c30a3273f92b3447cb22f4,bc230d8ee0d9503d4cd6081facd71f0e37a45fc2c475eae154da90ebee1ae087


Backend

https://mempool.space/liquid/api/tx/16e987d626adfa4dbf50312a9b8e31571531f9b8e5407c49d8e0b3dc4ac707ac#blinded=160252405,ce091c998b83c78bb71a632313ba3760f1763d9cfcffae02258ffa9865a37bd2,a50c70e9049a6a49f895b6bbadf7d4c212b1940b9748603fc006d3de1092bcbd,8b0ec267d4260102439c29abeb6fa606997cc4ee86fcd996bd82a462a78ee3c8,26252,6f0279e9ed041c3d710a9f57d0c02928416460c4b722ae3457a11eec381c526d,57bfaf037eea2f910e73c39e543306317ecda6d9e8c30a3273f92b3447cb22f4,bc230d8ee0d9503d4cd6081facd71f0e37a45fc2c475eae154da90ebee1ae087
