### ISSUE TITLE
[Login] Restore account should open fullscreen page

### ISSUE THREAD

**Issue by tiero** [vulpemventures/marina#116]
At the moment it shows the restor flow inside the shell popup﻿

**Comment by louisinger** [comment]
Do u mean "onboarding restorer flow"? It looks like this issue is closed if yes

**Comment by Janaka-Steph** [comment]
Yes, the Restore button on popup login screen had to open full screen onboarding restorer flow.

**Comment by tiero** [comment]
no, we need to activate a link/button in the bottom as per design, in the popup Login page, to force restore an account with seed


![image](https://user-images.githubusercontent.com/3596602/134318795-3905e00d-ac96-4558-a1d9-faefe860f5dd.png)


At the moment only way is to delete the extension and re-install
