### ISSUE TITLE
Transactions: Add specific labelling for Self Transfer

### ISSUE THREAD

**Issue by Janaka-Steph** [vulpemventures/marina#126]

**Comment by louisinger** [comment]
What does it mean ? Special icon / title for self transfer ? Or just "handle" self transfer tx ?

**Comment by tiero** [comment]
Yes I guess just handling and use a special title for it. Not sure about what the icon should be

**Comment by louisinger** [comment]
IMHO self-transfer is a kind of "deposit", because technically the wallet "receives" something. Deposit icon seems OK ?
