### ISSUE TITLE
Add `marina.getCoins`, `marina.getBalances` and `marina.getTransactions` and `marina.on` API

### ISSUE THREAD

**Issue by louisinger** [vulpemventures/marina#184]

**Comment by tiero** [comment]
Prefer calling it getUnspents or getCoins to be more explicit.

**Comment by louisinger** [comment]
maybe a `getBalances` could be useful too ?

**Comment by tiero** [comment]
Since we are at it, will put in place the `marina.on` to let clients subscribe to background script events such as new coins, new txs, wallet enabled/disabled etc..

Before implement we need to push into the `marina-provider` package
