### ISSUE TITLE
Marina Web Provider: SendTransaction : extend sendTransaction()  with new parameters

### ISSUE THREAD

**Issue by afarukcali** [vulpemventures/marina#214]
<img width="808" alt="Ekran Resmi 2021-09-06 14 39 36" src="https://user-images.githubusercontent.com/28007392/132211987-ebe7c816-c897-4583-b7bf-7f17fbb1fd2b.png">

Can you extend this function with **addresses** array and boolean **liquid_taxi** parameters ?

**Comment by tiero** [comment]
cc/ @vulpemventures/marina

Looks like we could abstract further and just add an optional parameter to choose the asset to be used for fees. 

`sendTransaction(recipients: AmountAndAsset, assetForFee: string)`

This way, for non L-BTC choices, external call to Liquid Taxi will be done to topup using the right asset.

Main concern is that this way we are "standardize" Liquid Taxi making as it was ubiquos, but after all this is the `MarinaProvider` so not really a standard Liquid Network Web provider
