### ISSUE TITLE
Marina Web Provider: add READY event type 

### ISSUE THREAD

**Issue by tiero** [vulpemventures/marina#215]
Useful to notify clients that Marina is injected (ie. is installed) otherwise apps need to resort to setInterval to keep checking after first mount 

https://github.com/tiero/brera/blob/master/src/components/Connect.svelte#L24

**Comment by louisinger** [comment]
AFAIK, it's not possible to add an "INSTALLED" event as a Marina event (for `marina.on` method) because `marina` will be undefined. We need to find a trick to "await" the injection phase.

**Comment by tiero** [comment]
You right. We actually have a DOM event emitted after injection, thinking a sane way to wrap this 🤔 

https://github.com/vulpemventures/marina/blob/master/src/inject-script.ts#L6

**Comment by tiero** [comment]
A pattern could be to expose in the `marina-provider` package as simple as the metamask `detect-provider`  https://github.com/MetaMask/detect-provider/blob/main/src/index.ts#L39

I would do something like this


```ts
const marina = new Marina(window.marina);
const marina = new Marina(window.customWebProviderInjectedByMarina);
```

Which will wait for the DOM event in the back
