### ISSUE TITLE
Having trouble Restoring using 24 word mnemonic seed from Green wallet

### ISSUE THREAD

**Issue by wksantiago** [vulpemventures/marina#236]
Having trouble Restoring using 24 word mnemonic seed from Green wallet

Getting following error:
Restoration failed
Encrypted mnemonic must be between 160 between and 192 chars

Retry

**Comment by tiero** [comment]
Hey @wksantiago 

Green mnemonic of 24 words is not compatible with Marina one, especially if you were using Liquid Multisig shield, which needs Blockstream server co-operation.

In case you are using Blockstream Green with Single Sig we only support in case of using addresses native segwit (ie. starting with `lq`)

AFAIK, Marina supports only menonics with 12 words created with Marina itself, with [TDEX App ](https://dev.tdex.network/docs/trader/app)and [Raretoshi](https://raretoshi.com/)

In general I suggest to have a separated mnemonic for Marina only.
