### ISSUE TITLE
adapt layout for Firefox 

### ISSUE THREAD

**Issue by tiero** [vulpemventures/marina#240]
At the moment is not responsive and well cut for Firefox, like decrease font in the Asset List

https://github.com/vulpemventures/marina/issues/240

**Comment by bordalix** [comment]
Some responsive bugs are independent from the browser used:

![Screenshot 2021-12-07 at 17 58 43](https://user-images.githubusercontent.com/9318412/145185290-537b91fe-9769-470f-b8ac-0db863862613.png)
![Screenshot 2021-12-07 at 17 59 41](https://user-images.githubusercontent.com/9318412/145185298-efc3bb15-e307-4eda-afc4-84a47650a3e9.png)
![Screenshot 2021-12-07 at 18 00 37](https://user-images.githubusercontent.com/9318412/145185304-82380bcb-87df-4218-8154-792e69fd3582.png)
![Screenshot 2021-12-07 at 18 33 35](https://user-images.githubusercontent.com/9318412/145185309-dbe3f19c-6c7a-4430-b0c6-0bb3b422a2bc.png)
![Screenshot 2021-12-07 at 18 34 47](https://user-images.githubusercontent.com/9318412/145185311-4408a2b1-ce76-4243-98e9-d372cab0e981.png)
![Screenshot 2021-12-07 at 18 38 15](https://user-images.githubusercontent.com/9318412/145185314-f7ef5394-71db-44fe-84dc-193ce655a5b4.png)
![Screenshot 2021-12-07 at 18 38 38](https://user-images.githubusercontent.com/9318412/145185316-a350d2e0-b152-410b-99e3-5d9ce2d50536.png)
:

**Comment by tiero** [comment]
What we have in "full screen" (ie. during on-boarding) is not responsive for mobile at all, mostly because Marina has been thought to be used on Desktop only, but this can change and would be a nice to have.

In the "popup" shell instead (the first screenshot you posted) it seems to me happening ONLY on FIrefox, not on chrome AFAIK
