### ISSUE TITLE
Support multiple script types

### ISSUE THREAD

**Issue by tiero** [vulpemventures/marina#250]
preliminary read: https://github.com/bitcoin/bitcoin/blob/master/doc/descriptors.md

In the eventuality to support custom scripts, beside "pay to pubkey" and "pay to multisig", having Marina supporting[ loading descriptors](https://github.com/vulpemventures/marina-provider/issues/11) would benefit developers of more advanced smart contracts/covenants, to have Marina to track custom script types.

At the moment we are [refactoring](https://github.com/vulpemventures/marina/pull/244) the domain to support many "accounts" which is a good first step, but we should abstract away the "bag of keys" model and embrace the output descriptor way, which means we are not constrained by having an account linked to a derivation path/extended public key (or collection of it in case of multisig)

## Current model

The new model will be as follow:

- We have a secret (mnemonic), we derive signing and blinding keys
- We have "Main Account"  with a default template ie. `wpkh(<xpriv|xpub>)`
- We have "2of2 Account" with a default template ie. `wsh(sortedmulti(2,<marina_xpriv>,<cosigner_xpub>))` (maybe more complicated with timelock stuff)
- We have N account(s) loaded arbitrary with descriptors we may want to keep track of. More complex scenario will be handled with `raw(SCRIPT)`

This will allow to keep track of balances and show in UI

## Importing descriptors

The loading of descriptor need to create extra metadata about `hasprivatekeys` when loaded with keys via `xpriv` (need to think about this if want to do thi, how we handle this keys etcc.) and `ownkeys` when we should use Marina's mnemonic to generate keys.

A suggestion can  be to have a special reserved keyword called `marina` so we can do things like `wsh(sortedmulti(2,marina,<cosigner_xpub>))` and we can fill there the marina xpub 

## Signing 

The signing get a bit tricky, since we need to have a way to link a script to a specific key, depending how we imported this. 

## Restore

This is tricky: since we can't know all the possible descriptors/complex raw scripts, user must backup also those and re-load after we restore from mnemonic later on. So dedicated API and/or UI must be designed.

PS: This is def something that could belong to `ldk` itself, but for recent experience, starting developing abstractions without being on the "ground" ie. wallet/ux development, would be much harder, so suggest to start desiging/modeling here and then port there.

**Comment by tiero** [comment]
Concrete use case: 

bitmatrix.app wants to create this kind of addresses:

```OP_1 OP_CHECKSEQUENCEVERIFY <PubKey> OP_CHECKSIG``` 

or as descriptor/miniscript
```and(pk(<PubKey>), older(1))```

we can for sure let web developers to fetch [the bare EC public key ](https://github.com/vulpemventures/marina-provider/issues/12) but this means we can't track the coins for that script anymore and [neither spend it](https://github.com/vulpemventures/ldk/blob/master/src/identity/masterpubkey.ts#L115-L121) since we always cache normal `wpkh(<PubKey>)` kind of addresses.

Assuming we let user give us a descriptor **template** with special marina keyword so we know to fill in the pub key, the challenge is that restoring from mnemonic will have the user load again these descriptors.

For the sake of supporting this specific use case quickly, we can have a dedicated account inside Marina that derives this special scripts always (need to think about the API tho), so it's easier to restore in the future

**Comment by tiero** [comment]
Thinking more in depth about this, especially to standardize a way to interact with different "account type" in the wallet via the Web Provider (singlesig, transfer resticted account, bitmatrix-generated timelocks script etcc.) a solution could be to do like Bitcoin Core and have dedicated API to create "Account/Wallet" where all the generated addresses will be derived starting from a descriptor.


example:

```js
// Increment the BIP44 account derivation and returns two xpubs, one per chain (internal/external). The name if not passed will be given one random
marina.createAccount("my_wallet") // => {external: xpubMain, internal: xpubForChange}

// Load wither a descriptor/miniscript/ASM template one for each chain
marina.setScriptTemplates(
 "my_wallet"
 {
   external: "wsh(and(older(1),pk(xpubMain)))", 
   internal:  "wsh(and(older(1),pk(xpubForChange)))"
 }
)

// set to use this account for future interactions
marina.setAccount("my_wallet")

// work with it 
marina.getNextAddress()
marina.sendTransaction()
...
```

**Comment by louisinger** [comment]
> ### setScriptTemplates
> 
> every time we override the default template ie. wpkh, we need to recognize if the given pub key is something that belong to our mneonic and flaf as "spendable" or not.
> 
> I do think starting with xpub only and NO support for externally loaded xpriv, is a good tradeoff, not sure how other use case, but they may be arise.

Why not associate each account with a script template? Something like:

```js
marina.createAccount(
 'single-sig', 
 {
   external: "wsh(and(older(1),pk(xpubMain)))", 
   internal:  "wsh(and(older(1),pk(xpubForChange)))"
 }
)
```

Then createAccount could "parse" the script templates and expect additional arguments if needed (in case of multisig for instance, we need to specify how to (1) get the blinding key and (2) sign the transaction):

```typescript
marina.createAccount(
 'multisignature-2-of-3',
 {
   external: "sortedmulti(2 ,key_1,key_2, key_3)", 
   internal:  "sortedmulti(2 ,key_1,key_2, key_3)"
 },
 {
   blindKey: "xorchaincode(key_1, key_2, key_3)", // this could be a constant
   signer: async (pset: base64) => {
       pset = await apiKey2.sign(pset);
       return key1.sign(pset);
       
   }
 }
```

**Comment by tiero** [comment]
> Why not associate each account with a script template? Something like:

This is my proposal, just with a dedicate method to "change" the script template. But yes can become a parameter of `createAccount` or both, this is just a cosmetic choice.

I am fan of having one method -> one duty to be more granular, but let's see.

> how to (1) get the blinding key

I do think here we should not let the user to shoot himself eventually using exotic approaches, so I would rather have sane defaults (ie. slip77 for singlesig and other custom scripts and xor (or whatever Andrew will propose next) for multisigs). Better to force standards here 

 > and (2) sign the transaction):
 
 This is a good point, but maybe is only the case of server cosigner 2of2 that needs it?
 
We could then have a dedicated API for this use case `setSigner` and then we pass a closure so the user can tweak the API endoint etc..

This is similar to the wrapping of the custom sighash we did with `approveSpend`

**Comment by tiero** [comment]
Updated proposals: use a custom BIP32 derivation path for complex scripts loaded from outside

When user visits a website which requires custom script to be imported, the website owner will give us a `app_name` string (cant prevent namespace collisions with other websites, this is up to the website owner to decided an enough unique string)   

The derivation path used will be then `m/ app_name' / change / index` where the `app_name'` should be the first 4 bytes of the hash of the given `app_name` string, converted to uint32 being sure is in range ` >= hardened_key_start e <= max_hardened_value` 


## Example

```js 

await marina.createAccount("my_webapp");

// from now on all the commands are ran against this account
await marina.useAccount("my_webapp");

// we must load the script template custom
const template = "wsh(OP_1 OP_CHECKSEQUENCEVERIFY <PublicKey> OP_CHECKSIG)";
await marina.importTemplate(template)

await marina.getNextAddress()
await marina.getNextChangeAddress() 

```
