### ISSUE TITLE
marina should add OP_RETURN in case of unblindable transaction

### ISSUE THREAD

**Issue by louisinger** [vulpemventures/marina#262]
Before blinding step, we should detect "unblindable" cases:
1. There are exactly 1 **confidential** input and 0 **confidential** outputs. 
2. There are exactly 0 **confidential** input and 1 **confidential** output.
3. There are exactly 1 **confidential** input and 1 **confidential** output. 

In these three cases, Marina should add a fake output using OP_RETURN and blind it in order to make the tx "blindable".

**Comment by tiero** [comment]
Should maybe be an LDK duty?
