### ISSUE TITLE
Transactions synchronization with Marina

### ISSUE THREAD

**Issue by louisinger** [vulpemventures/marina#271]
Marina provider lets web apps to create transactions using `sendTransaction`. The function **does not broadcast** tx but returns the signed hex transaction. Then the app is able to manually broadcast it using its own network node or explorer. From the marina point of view, we do not lock or mark as spent the utxos selected by `sendTransaction`. The only way to "spent" a marina utxo, is to wait for the explorer's response.

So, consider the following scenario :

```
let's imagine we run a Marina wallet with three unspent: U0, U1, U2

a. The web app creates a transaction T0 using `sendTransaction`. T0 is spending U0 and U1.
b. The web app broadcasts the transaction using its own node/explorer.
c. Marina doesn't know about the broadcast, so it has to wait for Esplora to index the newly confirmed transaction.
d. The web app recreates a transaction T1 and broadcasts it.
```
At point (d), there are two possibilities:
- either Marina got the time to update Utxos state in point (c), so T1 will select U2 and everything works correctly.
- or the web app creates the tx T1 before Marina receives the new blockchain state. **So T1 could re-select U0 and U1 causing a "missing inputs" error while broadcasting the transaction** even if, from the web app point of view, T0 has spent U0 and U1.

I see two ways to fix this "propagation issue": 
- either the web apps have to wait for Marina to update while they broadcast a transaction made by `sendTransaction` (using NEW_TX marina event for instance).
- or we provide an additional function in provider: `broadcastTransaction(hex: string)` which could "lock" the inputs before broadcasting the tx. (what if the app wants to use its own node?)

**Comment by tiero** [comment]
> or we provide an additional function in provider: broadcastTransaction(hex: string) which could "lock" the inputs before broadcasting the tx. (what if the app wants to use its own node?)

We eneded up always broadcasting the transaction in the `sendTransaction` API

**Comment by tiero** [comment]
I noticed in prolonged usage, that marina is not updating that much his utxo set. I always need to open the popup shell and enter in an asset detail page to trigger new one.

Is it browser.alarms not working anymore?
