### ISSUE TITLE
Wallet Error: Funding transaction cannot be created

### ISSUE THREAD

**Issue by cg-jusco** [vulpemventures/marina#272]
I created 2 transactions:
1.  Swap 0.0001 tL-BTC -> tL-USDt
2.  Swap 10 t-LUSDt -> tL-BTC

When I create the 2nd transaction before the first one is completed, I get the following error: 
Wallet Error: Funding transaction cannot be created
<img width="321" alt="Screen Shot 2022-01-07 at 11 34 45" src="https://user-images.githubusercontent.com/51105384/148482341-59fdce5e-5b23-4afa-ae4b-8e0afe1064d3.png">

I reached out to the Bitmatrix guys and they believe it's an issue with Marina.
I tried to Settings > Deep Restorer > Restore  to have a clean UTXO set and tried again.  
I still get the same error.

**Comment by tiero** [comment]
This may be linked https://github.com/vulpemventures/marina/issues/271
