### ISSUE TITLE
Bug after QR code to receive

### ISSUE THREAD

**Issue by bordalix** [vulpemventures/marina#277]
There are 2 bugs actually.

How to replicate:
1. Fresh install of the Chrome extension
2. Restore wallet (don't need to save mnemonic)
3. Click on LBTC
4. Click on Receive
5. Asks to save mnemonic (bug 1)
6. Click Save and it goes to QR code
7. Click back and you get a blank page (bug 2)

The component TransactionsView (called after step 7) has no `state` defined, so it blows.

If you click directly on Receive on the home screen, there's no issue:
1. Fresh install of the Chrome extension
2. Restore wallet
3. Click on Receive
4. Click Save and it goes to QR code
5. Click back and you go to the home screen

**Comment by tiero** [comment]
If you never "confirmed" you saved the mnemonic in the onboarding flow, we must ask you to do so first time you want to see a receiving adress.

When you say "Click Save and it goes.." you mean you need to go full screen and confirm the mnemonic?


instead If you already confirmed first time in onboarding, we should not show anything to the user

**Comment by bordalix** [comment]
It's an old wallet (well, at least one week old 😄 ) and the mnemonic its saved.
Also, I'm restoring the wallet, so it should assume is saved.

If I go HOME => RECEIVE => ASSET => QR Code => Back, everything is working
If I go HOME => ASSET => RECEIVE => QR Code => Back, the component blows

In the second flow, it asks me to save the mnemonic after clicking in RECEIVE.
