### ISSUE TITLE
Sutract fee when send amount equals to current LBTC balance

### ISSUE THREAD

**Issue by bordalix** [vulpemventures/marina#286]
If I try to send my total balance, an error is thrown (due to lack of funds for paying the fee), the catch() undefines `feeCurrency` so I lose the LBTC icon on the `Choose fee` component. See video:

https://user-images.githubusercontent.com/9318412/149127177-ceb5e7df-aae5-41ea-a19d-03871684f170.mov

I don't see the reason to undefine `feeCurrency`:

```
    } catch (err) {
      console.error(err);
      setErrorMessage((err as Error).message);
      setFeeCurrency(undefined); // Here
      setFeeChange(undefined);
      setTopup(undefined);
    }
```
in `src/presentation/wallet/send/choose-fee.tsx`

**Comment by tiero** [comment]
The most obvious fix is to recognize LBTC amount === LBTC balance and switch to "send all" mode ie. subtract fee

**Comment by bordalix** [comment]
Should I do it, or https://github.com/vulpemventures/marina/pull/244 will fix it?

I got that impression from https://github.com/vulpemventures/marina/pull/287 discussion.

**Comment by tiero** [comment]
not sure, Can you test with #244 PR this bug to confirm?

**Comment by bordalix** [comment]
@tiero tested with PR #244, works like a charm.
I think we can close this.
