### ISSUE TITLE
SEND ALL: Too many digitis

### ISSUE THREAD

**Issue by tiero** [vulpemventures/marina#295]
I got this balance in my wallet of USDt and clicking on SEND ALL I get "Too many digits" error

<img width="362" alt="image" src="https://user-images.githubusercontent.com/3596602/151955895-40d58312-3ca9-4eed-901f-ead057d0f5fd.png">

**Comment by bordalix** [comment]
Number of digits is limited to <14 here:
https://github.com/vulpemventures/marina/blob/master/src/presentation/components/address-amount-form.tsx#L153

Assuming the maximum number of satoshis is 2.1E15 (16 digits) and adding the possibility of managing milisatoshis, I would say <20 digits should be the new limit.
