### ISSUE TITLE
Unknown service Taxi

### ISSUE THREAD

**Issue by Janaka-Steph** [vulpemventures/marina#297]
Version: 0.3.7

<img width="1391" alt="Screenshot 2022-02-01 at 14 32 58" src="https://user-images.githubusercontent.com/4022128/151987825-60ac42b9-c61e-4c32-98fd-adff8fd48068.png">

**Comment by tiero** [comment]
Protobuf spec changed, working on a fix in #244. We know current master is not working with taxi

**Comment by tiero** [comment]
ref: https://github.com/vulpemventures/marina/issues/290
