### ISSUE TITLE
Send: unconfidential address validation throws warning and no feedback is shown to user 

### ISSUE THREAD

**Issue by tiero** [vulpemventures/marina#301]
trying to sending to unoncofidential address like `tex1q5vzqz46w7shu4ehwg8779kr8sgsfv39yf6d70g` for some reason returns a warning in the console (wich should not, is a valid address after all) but also no feeback in the UI when user clicks on the Verify button

<img width="2560" alt="image" src="https://user-images.githubusercontent.com/3596602/152650461-bec76a98-e701-4870-b09d-ebd6c39c2a10.png">

**Comment by tiero** [comment]
FYI: Liquid mainnet works (not sure for regtest but I suspect yes). Looks like something Testnet related since has been added recently to LiquidJS and LDK cc/ @louisinger

**Comment by bordalix** [comment]
Hummm...
@tiero why `ert` or `ex`?
Since this one starts with `tex` it assumes is a confidential address:
```
export function createAddress(
  address: Address['value'],
  derivationPath?: Address['derivationPath']
): Address {
  // Non Confidential
  if (address.startsWith('ert') || address.startsWith('ex')) { // <<=== HERE
    addressLDK.fromBech32(address);
    return {
      derivationPath: derivationPath,
      value: address,
    };
  } else {
    // Confidential
    const { blindingKey, unconfidentialAddress } = addressLDK.fromConfidential(address);
    return {
      value: address,
      blindingKey: blindingKey,
      derivationPath: derivationPath,
      unconfidentialAddress: unconfidentialAddress,
    };
  }
}
``` 

in https://github.com/bordalix/marina/blob/0f23d29250b263ab236bfab68c1fd79a353fee65/src/domain/address.ts#L16

**Comment by tiero** [comment]
mmm this code is crap 😓 it does not even take into account mainnet `lq` etc.. 🤦
