### ISSUE TITLE
Locking utxos

### ISSUE THREAD

**Issue by bordalix** [vulpemventures/marina#316]
After used in a transaction, utxos should be locked to prevent:
- double spending issues
- bloated balance (when change utxo is added to the set)

**Comment by bordalix** [comment]
Here is the plan:
- Selected coins should be added to the locker after a successful transaction
- When doing coin selection, locked utxos must be avoided (prevents double spending)
- Change transactions should be immediately available for better UX
- When calculating balance, locked utxos must not count for the final value (prevents bloated balances)

This means that `spend` and `send` must know which utxos where selected for the transaction and lock them.

My idea is to use this to store locked utxos:

```
    {
      ...state,
      unspentsAndTransactions: {
        ...state.unspentsAndTransactions,
        [accountID]: {
          ...state.unspentsAndTransactions[accountID],
          [network]: {
            ...state.unspentsAndTransactions[accountID][network],
            utxosMap: {
              ...state.unspentsAndTransactions[accountID][network].utxosMap,
            },
            lockedUtxos: {
              ...state.unspentsAndTransactions[accountID][network].lockedUtxos,
              [toStringOutpoint(utxo)]: 'locked',
            },
          },
        },
      },
    }
```

@louisinger @tiero any thoughts?

**Comment by louisinger** [comment]
> This means that `spend` and `send` must know which utxos where selected for the transaction and lock them.

We should use the [tdex-app logic](https://github.com/tdex-network/tdex-app/blob/a3bed0af4cea0cabaa6c440536cb1e2eb76f6de9/src/utils/helpers.ts#L181): it writes a custom coin selector from redux's Dispatch function --> each time the selector is selecting a coin, a LOCK_UTXO action is dispatched. 

Note that usually, the locked unspents should be unlocked after a certain amount of time (1 min for instance): it lets to ensure we get back the utxos if the transaction is never broadcasted for instance.

> ```
>     {
>       ...state,
>       unspentsAndTransactions: {
>         ...state.unspentsAndTransactions,
>         [accountID]: {
>           ...state.unspentsAndTransactions[accountID],
>           [network]: {
>             ...state.unspentsAndTransactions[accountID][network],
>             utxosMap: {
>               ...state.unspentsAndTransactions[accountID][network].utxosMap,
>             },
>             lockedUtxos: {
>               ...state.unspentsAndTransactions[accountID][network].lockedUtxos,
>               [toStringOutpoint(utxo)]: 'locked',
>             },
>           },
>         },
>       },
>     }
> ```

I don't think we need to store a locker for each network, 1 `lockedUtxos` cleaned if the network changes should be enough?

**Comment by bordalix** [comment]
> We should use the [tdex-app logic](https://github.com/tdex-network/tdex-app/blob/a3bed0af4cea0cabaa6c440536cb1e2eb76f6de9/src/utils/helpers.ts#L181): it writes a custom coin selector from redux's Dispatch function --> each time the selector is selecting a coin, a LOCK_UTXO action is dispatched.

Nice, thanks for the tip.

**Comment by bordalix** [comment]
> Note that usually, the locked unspents should be unlocked after a certain amount of time (1 min for instance): it lets to ensure we get back the utxos if the transaction is never broadcasted for instance.

So they should store the timestamp when they are locked, and every minute an alarm should clean up all locked utxos with timestamp less then X. It works.

**Comment by bordalix** [comment]
> I don't think we need to store a locker for each network, 1 `lockedUtxos` cleaned if the network changes should be enough?

Yes, it makes sense.
