### ISSUE TITLE
Sign taproot input

### ISSUE THREAD

**Issue by louisinger** [vulpemventures/marina#322]
related to #250 

with the introduction of Template based accounts, Marina should be able to sign a taproot input.

**Key path**
sign with schnorr, this is pretty similar of witness v0.

**Script path**
script path defines: spend a taproot coin via the leaf **L**

two cases:

1. either Marina has all the information needed to create the witness stack from **script(L)**: it means that **script(L)** only requires marina privkeys.
2. or Marina need an extra array of data **I**.

(1) the web dev could for instance specify the leaf (mapped with input index) in `signTransaction`.
(2) in that case, maybe better to let the user sign the pset and build the custom **I**. Note that we could add another `marina.getLeafInfo(L)` returning the path, the script and the taproot internal key (all the data needed to fill a script path witness stack).

**Comment by tiero** [comment]
>  Note that we could add another marina.getLeafInfo(L)

Uhm what would be the need for this? can't we add the path, scritp and internal key for the user to the input witness before making the signature?

**Comment by louisinger** [comment]
> > Note that we could add another marina.getLeafInfo(L)
> 
> Uhm what would be the need for this? can't we add the path, scritp and internal key for the user to the input witness before making the signature?

The user (webdev) could make the job but he needs the whole tree and key (then he uses bip341 functions on them to compute taproot witnesses). If marina provides a way to compute this, user could only care about the script's leaf. But maybe it's ok for the user to craft all the witness stack, anyway he will need to compute the script's input stack.
