### ISSUE TITLE
Add `marina.broadcastTransaction`

### ISSUE THREAD

**Issue by tiero** [vulpemventures/marina#341]
User can find this API useful to let Marina handle pushing tx to the network and eventually credit virtual change output if recognized

**Comment by bordalix** [comment]
@tiero, let me see if I correctly understood this: the idea is to have [this function](https://github.com/vulpemventures/marina/blob/master/src/application/utils/network.ts#L8) exposed in the marina provider API, is that it?

**Comment by tiero** [comment]
I think this function should do a) push transaction to explorer (yes doing what you linked b) scan for known change outputs like we do in `sendTransaction` and add a virtual utxo
