### ISSUE TITLE
Return "LDK compatible" utxos from `marina.getCoins`

### ISSUE THREAD

**Issue by tiero** [vulpemventures/marina#342]

**Comment by bordalix** [comment]
@tiero trying to understand what "ldk compatible" means.

From the Telegram conversation, I think it means to add `prevout` and `unblindData` to the coins returned by `marina.getCoins`. If this is correct, it means we need to:

1. Change the `Utxo` type on **marina-provider** by adding `prevout` and `unblindData`
2. Merge, bump version, deploy, and then update dependency on **marina**
3. Add missing keys to returned coins in `marina.getCoins` (we already have them on the returned JS object from `selectCoins(account)(state)`

Is this correct?

**Comment by tiero** [comment]
Merged and pushed to NPM
