### ISSUE TITLE
Move `MainAccount` base derivation path to standard coinType

### ISSUE THREAD

**Issue by tiero** [vulpemventures/marina#348]
After #345 is merged we should take this occasion to migrate the base derivation path to the standard Liquid one that uses 1776 as coinType for Liquid V1 and 1 for testnet,regtest etc...

**Comment by louisinger** [comment]
how the migration of current wallet should be done ? either we "force moving coins" or only newly created account will use the coinType ? same for restoration ? we should check/restore both paths ?

**Comment by tiero** [comment]
We simply scan for both derivation, since now we  will have this multi-account mode.

Current MainAccount becomes DeprecatedMainAccount and we switch to new one.

**Comment by tiero** [comment]
cc/ @altafan
