### ISSUE TITLE
`await marina.getAccountInfo()` returns undefine  for MainAccount

### ISSUE THREAD

**Issue by tiero** [vulpemventures/marina#355]
on MainAccount f I do `await marina.getAccountInfo()` will get `Uncaught Error: Account undefined not found`

_Originally posted by @tiero in https://github.com/vulpemventures/marina/issues/345#issuecomment-1145945204_

**Comment by louisinger** [comment]
GetAccountInfo expects an accountID as parameter: https://github.com/vulpemventures/marina-provider/blob/master/src/provider.ts#L48
Not the  expected behaviour ?

(The idea is to be able to get the info before switching)

**Comment by tiero** [comment]
We should return the main account info if undefined. Moreover, we should return the descriptor that represents the bip84 derivation
