### ISSUE TITLE
Rethink usage of custom script account

### ISSUE THREAD

**Issue by altafan** [vulpemventures/marina#365]
A custom script account can be seen as a special account with a special derivation path, where every generated internal/external keypair is associated with a very specific contract of the "same family", ie. they all have the same template.

Given this vision, the first thing a user should do is to create a new account by importing a template.
He, then, could generate the address for a specific contract by specifying its constructor arguments.
The user should use `getNextAddress(contructorParams)` to substitute the special account's namespace with an external pubkey, while `getNextChangeAddress(constructoParams)` should be used to does the same but with an internal pubkey.
To make the user's life easier, he should be able to specify constructor arguments as a JSON object containing strings or numbers values. Marina should take care of translating these args into "raw" types.
For this reason, at the moment only Ionio artifacts should be supported as template type. Marina descriptors lack in the definition of constructor args types, forcing the user to provide "raw" types which is not ideal. They still could be used as user info since it's an easy way for him to read a contract, therefore they will be returned as account's address info.

The concept of `changeTemplate` should be dropped since it makes no sense for the account to support a totally different template for internal keypairs.

**Comment by tiero** [comment]
> The concept of changeTemplate should be dropped since it makes no sense for the account to support a totally different template for internal keypairs.

There has been a lot of back and forth on this (refer to the https://github.com/vulpemventures/marina/issues/250 issue for history on the matter).

In short there could be occasion where you want to have a normal script (wpkh) as change and only custom one for the receiving part.

Concrete use case can be upcoming BitMatrix address which will be a timelocked script for receiving funds `and(after(1), pk($namesapce))` but marina should not encumber in a timelock his change when spending funds from the external chain, so user may want to decide a basic `wpkh($namespace)` as change template.

The behavior now is that if we do not pass anything to changeTemplate param, we use the receiving template
