### ISSUE TITLE
Make sure descriptor returned in getAccountInfo matches the one expected by neutrino-elements

### ISSUE THREAD

**Issue by tiero** [vulpemventures/marina#367]

**Comment by tiero** [comment]
ststus of this? @louisinger

**Comment by louisinger** [comment]
related to https://github.com/vulpemventures/ldk/pull/128 (in order to get the same master xpub on neutrino-elements & marina)

**Comment by tiero** [comment]
Merged!

**Comment by louisinger** [comment]
@tiero I think also related to https://github.com/vulpemventures/marina/pull/361. 
The descriptor expected by neutrino-elements is `wpkh("masterxpub")` but #361 returns `elwpkh($mainAccount)`. 

I do think we should migrate to "el"-like template in neutrino-elements, or marina returns wpkh maybe? what about the token $mainAccount, let's drop it in favor of masterXPub ?

**Comment by tiero** [comment]
> I do think we should migrate to "el"-like template in neutrino-elements

Yes this has been fixed already

> what about the token $mainAccount, let's drop it in favor of masterXPub

Yes `descriptor` shoudl always be the final one, witohut template strings
