### ISSUE TITLE
We should not sum the fee amout in outbound 

### ISSUE THREAD

**Issue by tiero** [vulpemventures/marina#402]
In this transaction I did making a swap on BitMatrix history is not correct:

1) We show two items, one Swap and one Received (look at L-BTC history). We should have shown only one
2) Inside the swap item, The Outbound `-12 FUSD` is correct 
3) Inside the swap item, The Outbound L-BTC is NOT correct `-0.00001201` (is that the change? Don;t really know since cant unblind the change output)
4) We have an extra item, the Received, which is correct.  

<img width="309" alt="image" src="https://user-images.githubusercontent.com/3596602/187879548-a52dd941-38ef-441a-baa0-f8774cd08706.png">

<img width="365" alt="image" src="https://user-images.githubusercontent.com/3596602/187879937-309fb6aa-cfc3-4fac-9deb-6e8c46b80c8d.png">

<img width="320" alt="image" src="https://user-images.githubusercontent.com/3596602/187879997-9fe31277-7e7b-47ec-bae2-68188e93e48c.png">

<img width="317" alt="image" src="https://user-images.githubusercontent.com/3596602/187880039-ee75208f-678e-4940-998f-8233186bb7b5.png">

https://liquid.network/testnet/tx/e5f62939146afa6c98df273ae8de3766779cf1444fa208a628145df926e34eb4#blinded=701,144c654344aa716d6f3abcc1ca90e5641e4e2a7f633bc09fe3baf64585819a49,0000000000000000000000000000000000000000000000000000000000000000,0000000000000000000000000000000000000000000000000000000000000000,1200000000,0d86b2f6a8c3b02a8c7c8836b83a081e68b7e2b4bcdfc58981fc5486f59f7518,0000000000000000000000000000000000000000000000000000000000000000,0000000000000000000000000000000000000000000000000000000000000000,6603115,144c654344aa716d6f3abcc1ca90e5641e4e2a7f633bc09fe3baf64585819a49,97286ad7dbb6165e3f99804ce376a1d74a2e80ef261fc240f745e0afa77fe69f,d236ea8178fbf12e64e0e0c86a5cd044aeb9ecc489163ce240931bb31948ac51,0,144c654344aa716d6f3abcc1ca90e5641e4e2a7f633bc09fe3baf64585819a49,0000000000000000000000000000000000000000000000000000000000000000,0000000000000000000000000000000000000000000000000000000000000000

**Comment by tiero** [comment]
ok is actually all correct for how BitMatrix work

Only bug is we sum the fee output in the Outbound of the first transaction

![image](https://user-images.githubusercontent.com/3596602/187884236-9516e5fe-978e-4251-9047-c642d822162d.png)
![image](https://user-images.githubusercontent.com/3596602/187884258-6809ab2f-cba5-40ce-bfa3-b6687d89bff0.png)

**Comment by louisinger** [comment]
deduct the fees amount from Outbound only make sense in case you are paying the fees. if the other stakeholder pay the L-BTC fees, the outbound will be wrong.

while receiving & unblinding a transaction, Marina doesn't know the asset/amount of non-wallet inputs and outputs (let's suppose all are confidential cause that's the most common case). In your transaction -0.00001201 is `your_lbtc_input_value - your_lbtc_change_value`: there is no way to know if u directly send all the L-BTC in other output OR if that value includes the fee amount. 

we could deduct the value of the fees if an outbound lbtc is present but there would still be cases where the value would be wrong (if another input is responsible for paying the transaction fees) cc @tiero
