### ISSUE TITLE
Promise.all does not work correctly with marina.getNext*Address methods

### ISSUE THREAD

**Issue by louisinger** [vulpemventures/marina#403]
```js
await Promise.all([marina.getNextChangeAddress(), marina.getNextChangeAddress()])
```
returns the same address for both calls (both are using the same redux state to generate the addresses).

**Comment by louisinger** [comment]
I'm not sure this can be solved, by definition Promise.all call both code at the same time and marina don't have a way to detect such case

**Comment by tiero** [comment]
Yes only way is

```
for (const item of items) {
  await marina.getNextChangeAddress ()
}
```
