### ISSUE TITLE
getNextAddress is blocking

### ISSUE THREAD

**Issue by ErikDeSmedt** [vulpemventures/marina#405]
When doing

```
await window.marina.getNextAddress();
```

the entire page freezes for a couple of seconds. I would expect the page to remain usable whilst an address is being loaded.

**Comment by tiero** [comment]
Thanks for opening this! 

Is the wallet with lot of history by any chance?

**Comment by ErikDeSmedt** [comment]
Depends on what you consider a lot. 
I have generated about 1000 addresses using this wallet.

**Comment by louisinger** [comment]
@ErikDeSmedt, is it possible to share the app code using the marina provider ?

**Comment by ErikDeSmedt** [comment]
This is the code we are using to generate the address.

```javascript
let marina = await getProvider();
let address  = (await marina.getNextAddress())?.confidentialAddress;
```

PS:
On my current set-up the `getNextAddress()` resolves immediately and I cannot replicate the issue

**Comment by tiero** [comment]
> On my current set-up

But with the same mnemonic ie. 1000+ addresses generated or a new one?

**Comment by ErikDeSmedt** [comment]
It  has the same mnemonic.

However, not all these addresses have received funds.
If I do `window.marina.getAddresses()` the list is considerably shorter and only contains 50 addresses.

It seems my current wallet is not aware of the generated addresses.

**Comment by ErikDeSmedt** [comment]
I managed to reproduce the behavior.

I generated 1000 address by pasting the snippet below in the chrome console. The script took approximately 40 minutes.

```javascript
// Generate 1000 addresses and capture the timing
for (let iii=0;iii<1000;iii++) { 
  await (async () => { 
    let start = performance.now();
    await window.marina.getNextAddress();
    let end = performance.now();
    console.log({"index" : iii, "timing" : end-start}); 
  })();
}
```

It seems that `genNextAddress()` becomes slower if you generate more addresses.
![image](https://user-images.githubusercontent.com/2528683/191948769-d3cc1348-405e-44da-a0af-43174d1eb8f4.png)

Once the script is executed you can go into your browser console and do.
```
window.marina.getNextAddress();
```

You'll notice the tab does not respond for a couple of seconds.
