### ISSUE TITLE
Refacto the transactions updater architecture

### ISSUE THREAD

**Issue by louisinger** [vulpemventures/marina#416]
### How it works now

The current updater is running in background via redux-saga. An update is launch each time an UPDATE_TASK action is dispatched in the store. 
1. [getTxsGenerator](https://github.com/vulpemventures/marina/blob/d160298eb9ed57ab0851974a8df9b090e5a139c9/src/application/redux/sagas/updater.ts#L123-L145) gets the account to update and extract all the addresses (from the current state of the store). Then it launches several LDK generators (txsFetchGenerator) to **fetch and unblind** transactions from the explorer.
2. The results (= the unblinded txs as `TxInterface`) of all generators are [sent to redux-saga channel](https://github.com/vulpemventures/marina/blob/d160298eb9ed57ab0851974a8df9b090e5a139c9/src/application/redux/sagas/updater.ts#L226).
3. That channel is connected to a [txsTransformerWorker](https://github.com/vulpemventures/marina/blob/d160298eb9ed57ab0851974a8df9b090e5a139c9/src/application/redux/sagas/updater.ts#L306-L314) which is a function converting `ldk.TxInterface` (from the channel) to an internal interface named `TxDisplayInterface`.
4. `TxDisplayInterface` has a `transfers` member used in UI to compute the user-friendly informations about the transaction (Inbound & outbound values). In order to do this, the worker is recomputing **all the wallet scripts from state** and send them with the tx in [getTransfers](https://github.com/vulpemventures/marina/blob/d160298eb9ed57ab0851974a8df9b090e5a139c9/src/application/utils/transaction.ts#L395) function.
5. the `TxDisplayInterface` object is the one persisted in redux state. once fetched, unblinded and computed, `TxInterface` is not accessible anymore by the UI.

### The problem

The steps (1) and (4) are really sensitive because they need the wallet scripts. But those scripts come from the accounts `restorerOpts` (the last internal/external indexes) from state. If for any reason, the state is not up to date in background during the execution of step (1) or (4), the `TxDisplayInterface` will be wrong and UI will display bad informations to the user.

### Proposals

I see two refactors to fix the update txs process:

**A:** We persist `TxInterface` in the redux state instead of `TxDisplayInterface`, getTransfers is executed only while needed in the UI. It means the UI reflects exactly the current state value (inbound/outbound are computed when user is looking at tx history, not during the update step).

**B:** Add an event based unblinder worker. Fetching & unblinding would be triggered by the UPDATE_TASK exactly like it works currently. But INCREMENT_*_INDEX actions could also trigger an unblind process, iterating through persisted `TxInterface` in the state and trying to unblind outputs associated with the address' script. 

cc @tiero @altafan

**Comment by tiero** [comment]
I think we should explore a deep refactor of current architecture eventually, I think B option is the browser extension way (ie. event driven) to have less coupling between components and most importantly to work nicely in a context where users can open/close browser etc...

**Comment by altafan** [comment]
What is the impact of A)? It sounds like a breaking change for a user updating from a previous version. He would have a list of `TxDispalyInterface` in the redux store, while marina would now expect a list of `TxInterface`. We may want to have both instead, but I honestly prefer option B).

Incementing the index means generating a new address, and that must be known by the component that fetches and unblinds utxos for sure.

**Comment by louisinger** [comment]
> What is the impact of A)?  It sounds like a breaking change for a user updating from a previous version. He would have a list of `TxDispalyInterface` in the redux store, while marina would now expect a list of `TxInterface`.

for the user nothing because he is not using directly the store. A needs some migration logic but we already did it in the past (basically, u clean the whole txs state to force refetch all at the next update).

> We may want to have both instead, but I honestly prefer option B).

Was not clear my bad but B needs A because `TxDisplayInterface` does not have enough data to handle unblinding so to implement B we need a change in the transactions state.

**Comment by louisinger** [comment]
closed by #436
