### ISSUE TITLE
Chose fee: we shoudl show the L-BTC logo, not the one of the asset we are sending

### ISSUE THREAD

**Issue by tiero** [vulpemventures/marina#420]
https://www.loom.com/share/ad654c3f4e0e4f3b8935799cd493c4af

**Comment by altafan** [comment]
I actually don't understand the value `0.39243994` shown. It seems to me that the logo is actually correct because you're sending 1000 fUSD. I just would have expected value `1000.00` under that logo.

Am i missing something?

**Comment by louisinger** [comment]
According to zeplin, the logo and balance should be the one of the **selected fee asset**. https://zpl.io/VKXeeYE
Note that the "not selected yet" case isn't handled however in zeplin, I would let L-BTC by default and change logo/balance if USDT or other assets are selected

**Comment by altafan** [comment]
Agreed, i would also show the fee amount to pay in LBTC by default, even if no asset selected yet
