### ISSUE TITLE
Nit: inconsistent layouts.

### ISSUE THREAD

**Issue by bordalix** [vulpemventures/marina#429]
I sampled 4 different Marina layouts, where we have an input/select field and a button.

Notice how they are different:
1. Network selection (no button)
2. Explorer selection (button aligned right, near select field)
3. Restoration gap limit (button aligned center, near select field)
4. Unlock (button aligned right, at the bottom of the screen)

Also:
5. Do we need a button on Explorer selection? Can't we act only on select and remove the button?

Question: what should be the default layout?
![Screenshot 2022-10-13 at 11 17 57](https://user-images.githubusercontent.com/9318412/195575393-8cf85169-95f8-40c4-9433-c0a87777a4e3.png)
![Screenshot 2022-10-13 at 11 15 21](https://user-images.githubusercontent.com/9318412/195575399-45a42789-c61e-4bf6-aaf9-74857d457e99.png)
![Screenshot 2022-10-13 at 11 15 10](https://user-images.githubusercontent.com/9318412/195575403-49a59b56-e5c5-457e-84b2-98f358304923.png)
![Screenshot 2022-10-13 at 11 14 57](https://user-images.githubusercontent.com/9318412/195575406-df965cb9-ced6-450b-9c8e-1c6a44fb3fe0.png)

**Comment by tiero** [comment]
> 5. Do we need a button on Explorer selection? Can't we act only on select and remove the button?

only when custom is selected and inputs are shown
