### ISSUE TITLE
Close contract tx never appear in tx list

### ISSUE THREAD

**Issue by bordalix** [vulpemventures/marina#444]
1. Initial funding (+234)
2. Borrow FUSD (+7)
3. Close contract (-7) missing
4. Borrow FUSD (+8)
5. Close contract (-8) missing

![Screenshot 2023-03-21 at 15 58 05](https://user-images.githubusercontent.com/9318412/226666873-09ffc04a-9fd4-4812-a752-438f989788fc.png)

**Comment by tiero** [comment]
@louisinger status?
