### ISSUE TITLE
LBTC tx used in contract creation don't show on tx list

### ISSUE THREAD

**Issue by bordalix** [vulpemventures/marina#445]
Related to #444 

There were 2 contract creations on March 21 that don't show up here.

![Screenshot 2023-03-21 at 15 59 39](https://user-images.githubusercontent.com/9318412/226667854-c6a61d1a-d676-4551-b36f-f951695f2b9b.png)

**Comment by tiero** [comment]
Status? @louisinger

**Comment by louisinger** [comment]
Contract are shown under the fuji asset transactions list. From L-BTC point of view, borrow only moves coins from an account to another one (a kind of self-transfer) which is not displayed cause there is another asset in the tx (that's how marina "detects" self transfer tx).

I think the point here is how to identify correctly covenant-based transaction

**Comment by tiero** [comment]
I do think it's fine to show the L-BTC deposit into other accounts as "external" recipients for the time being

**Comment by tiero** [comment]
Closing, let me know if need to be re-open
