### ISSUE TITLE
Registered asset amounts are not being formatted with precision in spend.tsx

### ISSUE THREAD

**Issue by Randy808** [vulpemventures/marina#449]
When the `marina.sendTransaction` is called from the api, the popup from sign.tsx doesn't format the amount with the precision found within the registry

The asset in the picture below has a precision of 0 but is shown with a precision of 8:
<img width="354" alt="Screenshot 2023-03-23 at 5 53 34 AM" src="https://user-images.githubusercontent.com/4742100/227167140-abd20bc0-6b89-434e-9700-1c67b49a508e.png">

**Comment by louisinger** [comment]
@tiero still present in master, should be fixed by #450
