### ISSUE TITLE
`onboarding/end-of-flow` should handle the whole restoration process

### ISSUE THREAD

**Issue by louisinger** [vulpemventures/marina#457]
### Current behavior

With manifest v3 refacto, the process of "wallet restoration" is divided into 2 steps:
1. find the scripts/addresses to restore via bip32 restore strategy.
2. fetch and unblind the transactions associated with that addresses.

(1) is done in `onbaording/end-of-flow` page.
(2) is triggered by the `Updater` service in `background-script.ts`

### Expected behavior

(1) & (2) should be done in `onbarding/end-of-flow` context with an appropriate "loading state" showing what's restored by the wallet.

**Comment by tiero** [comment]
We decided offilne to show the marina spinner in the onboarding page until the restoration is not done.
