### ISSUE TITLE
Withdraw amount not correct

### ISSUE THREAD

**Issue by Janaka-Steph** [vulpemventures/marina#483]
I notice that the amount in withdraws is not correct. Most likely that example tx sent 0.001 lbtc including fees. It seems that the amount is adding fees twice.

<img width="1253" alt="Screenshot 2023-06-14 at 21 58 41" src="https://github.com/vulpemventures/marina/assets/4022128/66bb479d-7dcb-4490-9351-edb6227e94b3">
<img width="374" alt="Screenshot 2023-06-14 at 21 59 12" src="https://github.com/vulpemventures/marina/assets/4022128/d4fd73d9-b3f4-4f3d-8455-252a74206a60">

**Comment by tiero** [comment]
@louisinger

**Comment by louisinger** [comment]
The tx is sending 0.0001 + fees isn't it ? The unblinded output in explorer screenshot is the change and you have two inputs (I guess two  0.0001 faucet from testnet). I may be wrong but if you sent that tx using the UI without send max button, it's the expected behaviour.

**Comment by Janaka-Steph** [comment]
@tiero @louisinger Ok yes your interpretation is correct. The fee is not counted twice in the send amount. 

However, should we add the fee to the send amount?
Here I withdraw 0.00005 LBTC from Green mobile
![IMAGE 2023-06-19 12:09:21](https://github.com/vulpemventures/marina/assets/4022128/5898040f-1f3e-4005-a2d4-69f1e903a577)
![IMAGE 2023-06-19 12:09:26](https://github.com/vulpemventures/marina/assets/4022128/c6ac0e8a-87ec-4e72-b518-1d69fbf5adf4)
On transaction list screen the fee is added to the amount. But clicking to tx detail it shows send amount and fees separately. I think it's the best approach.

In Marina the transaction list is correct, but Outbound amount should be the send amount without fee.
What do you think?

**Comment by louisinger** [comment]
> but Outbound amount should be the send amount without fee. What do you think?

Yes u're right, I'll detuct the fee amount from withdraw. However, it should be done only if we own all the inputs, in others cases how do we know if we pay the fees? I'm thinking about swaps for instance: maybe I'm swapping 1 L-BTC for 10 shitcoins without paying the tx fees. In such case, deducting the fees will show swaps as 1-fees  <=> 10 shitcoins

**Comment by Janaka-Steph** [comment]
Yes, it's relevant only for withdraws
