### ISSUE TITLE
Wrong tL-BTC amount sent to extension from marina.sendTransaction

### ISSUE THREAD

**Issue by jamesdorfman** [vulpemventures/marina#490]
I am running the following request to the marina wallet API from Google Chrome v115, as described in the API docs:
```
const submitTxClick = async (liquidAddr) => {
  const { txid, hex } = await window.marina.sendTransaction(
    [
      {
        address: liquidAddr, // the address of the recipient
        asset: "144c654344aa716d6f3abcc1ca90e5641e4e2a7f633bc09fe3baf64585819a49", // test bitcoin
        value: 10000 // amount always expressed in satoshis
      }
    ],
  );
}
```

The actual transaction is sent correctly. However, before it is sent the confirmation window displays the incorrect balance:

<img width="564" alt="Screenshot 2023-08-15 at 4 55 16 PM" src="https://github.com/vulpemventures/marina/assets/6634974/6d0d464f-dad1-4ff5-946a-75f2fa72c1d6">

This balance reads 8 no matter what value I pass into the API request.

I think this is likely related to the fact that I am running on testnet, and using test L-BTC. It is solely a UI bug, since the actual transaction ends up being broadcast with the right amount. Let me know what other information you need to reproduce this bug. Thanks!

**Comment by louisinger** [comment]
Indeed, some typo error in jsx component was diplaying the precision only. PR #491 should fix it, fill free to review it & test. Thanks for reporting, much appreciated :+1:
