### ISSUE TITLE
Show the balance of BTC with whitsepace every 3 digits

### ISSUE THREAD

**Issue by tiero** [vulpemventures/marina#503]
ie. from 0.00004411 to 0.00 004 411

You could also make the middle triple to be bolder

**Comment by bordalix** [comment]
@tiero should we always show 8 decimal numbers?

**Comment by bordalix** [comment]
@tiero sorry, I didn't understand you: what do you mean is easier to copy paste the "sats" component?
The part that is selected on the image? Or only the last 3 digits?

![Screenshot 2023-12-19 at 17 49 57](https://github.com/vulpemventures/marina/assets/9318412/a5075911-9e69-48b6-84f4-cf81bef3cdba)

**Comment by tiero** [comment]
If you don't always show decimals, it means that if you have 10k sats, you will cut the last three digits because they are zeros, and it's hard to copy-paste `0.00001` in an app that expects sats. Its just a minor :D but to say best to always show all the decimals

**Comment by bordalix** [comment]
Ahhh, yes, it's easier to copy with 8 decimal numbers, indeed.
But with spaces in between, it isn't again 😉
