### ISSUE TITLE
Asset did not arrive

### ISSUE THREAD

**Issue by Impa10r** [vulpemventures/marina#538]
I [paid](https://blockstream.info/liquidtestnet/tx/934c530021eded9c86176b65f70516390dd35da04074d33d9acf2573b402d0a7#blinded=975468150,b612eb46313a2cd6ebabd8b7a8eed5696e29898b87a43bff41c94f51acef9d73,059fb31b187a840798ee4283bd08bed8d34b9052fc9c08df0b70188959453e38,8578ce32a37035dbf4d3555cad06a255b0e6fa28a851b5d7d409868d20c1e817) 9.75 PEGx USDT testnet from Elements to Marina, to an address that Marina generated. The deposit was lost. I waited for an hour and refreshed many times.

Trying "deep restore" got me this: 

restoration loading...
A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received

Is it possible to import/restore the seed phrase from Marina into Elements to investigate such cases? Otherwise, the wallet is unsafe.

**Comment by tiero** [comment]
Can you try restore your Marina wallet seed? That should trigger proper discovery I think. I am thinking that for some reason Marina didn't derive all new addresses.

Can you also post the transaction hash so we can inspect?

Elements does not support Bip32/Bip44 so you would have to derive keys and import them one by one via JSONRPC

**Comment by tiero** [comment]
I saw you liked the tx in OP, nvm.

The address seems a native segwit indeed. Try to restore wallet from your mnemonic, that should trigger a full rescan

**Comment by Impa10r** [comment]
Yes, after restoring the UTXO appeared. Thanks.

**Comment by Impa10r** [comment]
Just happened again, with BTC. Not a reliable wallet :(

**Comment by tiero** [comment]
First time it's happening in a consistent way. Which browser are you using? Also consider that we connect to public websockets of Blockstream to use Electrum protcol. We had many issues, usually switching to your own Electrum node is always recommended

**Comment by Impa10r** [comment]
> First time it's happening in a consistent way. Which browser are you using? Also consider that we connect to public websockets of Blockstream to use Electrum protcol. We had many issues, usually switching to your own Electrum node is always recommended

Opera for Windows. Also, the wallet stutters all the time for 3-4 seconds, to display new address or to calculate a transaction fee. Sometimes if does not finish calculating and needs to be closed on opened again. This happens more if some heavy website is opened and I guess less resources (RAM?) are available for the wallet.
