### ISSUE TITLE
[Refactoring] Not mocking uuid in tests

### ISSUE THREAD

**Issue by Janaka-Steph** [vulpemventures/marina#62]
Currently we are mocking `uuid` library to return a fixed value 'test-id' in order to compare received from expected values. It is handy but introduces issues.

It forces us to have a check in codebase that should not be there, `getOrCreateWallet()` method from `browser-storage-wallet-repository.ts`.
```
      // this check is only for testing purpose
      if (
        store.wallets.findIndex(
          (storeWallet) => storeWallet.walletId === w.walletId.id.toString()
        ) < 0
      ) {
        newStorageWallets.push(WalletMap.toDTO(w));
      }
```

More importantly, a fixed uuid value breaks Entity original behaviour of having an identity and be different from one another. Entities in tests should not behave differently than in codebase.

We can solve this issue by removing the uuid mock and using flexible property matchers like [expect.any(UniqueEntityID)](https://jestjs.io/docs/en/expect#expectanyconstructor) (for Entities) and `expect.stringMatching(/^[0-9A-F]{8}-[0-9A-F]{4}-4[0-9A-F]{3}-[89AB][0-9A-F]{3}-[0-9A-F]{12}$/i)` (for DTOs).

Also in some places, `toStrictEqual()` should be replaced by [toMatchObject()](https://jestjs.io/docs/en/expect#tomatchobjectobject).

**Comment by louisinger** [comment]
outdated by PR #178 ? cc @tiero
